### ISSUE TITLE
Why is naive-ui in devDependencies not in dependencies?

### ISSUE THREAD

**Issue by Ping-Gao** [id88/wails-vite-vue-ts-navie-pinia#1]
为什么 naive-ui在devDependencies里面，一般前端构建的时候是不会把devDependencies打包的。wails build是不对devDependencies和dependencies做区分默认打包所有的吗？

Why is naive-ui in devDependencies? Usually when we do deploy, dependencies in devDependencies will not get build into the final  bundle. Does the wails build did not differentiate  devDependencies and dependencies, it just build everything by default?

Thanks in advance!

**Comment by id88** [comment]
> 为什么 naive-ui在devDependencies里面，一般前端构建的时候是不会把devDependencies打包的。wails build是不对devDependencies和dependencies做区分默认打包所有的吗？
> 
> Why is naive-ui in devDependencies? Usually when we do deploy, dependencies in devDependencies will not get build into the final bundle. Does the wails build did not differentiate devDependencies and dependencies, it just build everything by default?
> 
> Thanks in advance!

据我所知，wails build 是加载已经打包好的前端资源(dist目录里面的文件)。这里前端构建的时候是使用Vite ，默认情况下确实不会打包 devDependencies，至于这里为什么放在devDependencies 里面程序也可以正常运行，可能是因为使用了 `unplugin-auto-import/vite` 和 `unplugin-vue-components/vite` 这两个插件。
